# Generated by Django 4.1.3 on 2022-11-30 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='bonus_write_off',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='order.order'),
        ),
        migrations.AlterField(
            model_name='purchasecountable',
            name='quantity',
            field=models.SmallIntegerField(default=1),
        ),
    ]
