# Generated by Django 4.1.3 on 2023-01-04 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_bonuses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date_full_refund',
        ),
    ]
