# Generated by Django 4.1.3 on 2023-01-04 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_remove_order_date_full_refund'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='is_full_paid',
            new_name='is_paid',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_timeout',
        ),
        migrations.AddField(
            model_name='purchase',
            name='is_prepayment_paid',
            field=models.BooleanField(default=False, verbose_name='Предоплата внесена'),
        ),
    ]
