# Generated by Django 4.1.3 on 2023-01-05 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_rename_is_full_paid_purchase_is_paid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='bonus_write_off',
        ),
        migrations.AddField(
            model_name='order',
            name='paid',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=12),
        ),
    ]
