# Generated by Django 4.1.3 on 2023-01-21 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_alter_service_max_intersections'),
        ('order', '0006_purchase_is_canceled_purchase_is_refund_made'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasecountable',
            name='timetable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchases', related_query_name='purchase', to='service.servicetimetable'),
        ),
    ]
