# Generated by Django 4.1.3 on 2023-01-21 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_purchasecountable_timetable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasecountable',
            name='timetable',
        ),
    ]
