# Generated by Django 4.1.3 on 2023-01-24 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_remove_order_bonuses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Оплачено'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='prepayment',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='refund',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
