# Generated by Django 4.1.3 on 2023-01-24 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_alter_order_paid_alter_purchase_prepayment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-date_create']},
        ),
        migrations.AddField(
            model_name='order',
            name='refunded',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Возвращено'),
        ),
    ]
