# Generated by Django 4.1.3 on 2023-02-15 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0024_alter_offer_price_type'),
        ('order', '0012_alter_order_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='offer.offer'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='order.order'),
        ),
    ]
