# Generated by Django 4.1.3 on 2023-02-16 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_alter_purchase_offer_alter_purchase_order'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['paid', 'refunded', 'date_create'], name='order_order_paid_d2febe_idx'),
        ),
    ]
