# Generated by Django 4.1.3 on 2022-11-30 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='наименование')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('default_price', models.DecimalField(decimal_places=5, max_digits=12, verbose_name='стандартная цена')),
                ('weekend_price', models.DecimalField(decimal_places=5, max_digits=12, verbose_name='цена по праздникам')),
                ('prepayment_percent', models.FloatField(verbose_name='предоплата')),
                ('refund_percent', models.FloatField(verbose_name='возврат')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('date_deleted', models.DateTimeField(blank=True, null=True, verbose_name='дата удаления')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='скрыто')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('rooms', models.SmallIntegerField(verbose_name='комнат')),
                ('floors', models.SmallIntegerField(verbose_name='этажей')),
                ('beds', models.SmallIntegerField(verbose_name='спальных мест')),
                ('square', models.FloatField(verbose_name='площадь')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='наименование')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('default_price', models.DecimalField(decimal_places=5, max_digits=12, verbose_name='стандартная цена')),
                ('weekend_price', models.DecimalField(decimal_places=5, max_digits=12, verbose_name='цена по праздникам')),
                ('prepayment_percent', models.FloatField(verbose_name='предоплата')),
                ('refund_percent', models.FloatField(verbose_name='возврат')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('date_deleted', models.DateTimeField(blank=True, null=True, verbose_name='дата удаления')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='скрыто')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('max_for_moment', models.SmallIntegerField(verbose_name='макс. единовременно')),
                ('dynamic_timetable', models.BooleanField(verbose_name='динамическое расписание')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['date_deleted', 'is_hidden'], name='offer_servi_date_de_2435be_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['slug'], name='offer_servi_slug_7735a0_idx'),
        ),
        migrations.AddField(
            model_name='room',
            name='main_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child_rooms', related_query_name='child_room', to='offer.room', verbose_name='номер представитель'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['date_deleted', 'is_hidden'], name='offer_room_date_de_55da4f_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['slug'], name='offer_room_slug_7eef96_idx'),
        ),
    ]
