# Generated by Django 4.1.3 on 2022-12-03 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='наименование')),
                ('description', models.TextField(verbose_name='описание')),
                ('default_price', models.DecimalField(decimal_places=5, max_digits=12, verbose_name='стандартная цена')),
                ('weekend_price', models.DecimalField(decimal_places=5, max_digits=12, verbose_name='цена по праздникам')),
                ('prepayment_percent', models.FloatField(verbose_name='предоплата')),
                ('refund_percent', models.FloatField(verbose_name='возврат')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('date_deleted', models.DateTimeField(blank=True, null=True, verbose_name='дата удаления')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='скрыто')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('offer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='offer.offer')),
                ('max_for_moment', models.SmallIntegerField(verbose_name='макс. единовременно')),
                ('dynamic_timetable', models.BooleanField(verbose_name='динамическое расписание')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('offer.offer',),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('offer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='offer.offer')),
                ('rooms', models.SmallIntegerField(verbose_name='комнат')),
                ('floors', models.SmallIntegerField(verbose_name='этажей')),
                ('beds', models.SmallIntegerField(verbose_name='спальных мест')),
                ('square', models.FloatField(verbose_name='площадь')),
                ('main_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child_rooms', related_query_name='child_room', to='offer.room', verbose_name='номер представитель')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('offer.offer',),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['date_deleted', 'is_hidden'], name='offer_offer_date_de_5a9be7_idx'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['slug'], name='offer_offer_slug_eccef5_idx'),
        ),
    ]
