# Generated by Django 4.1.3 on 2022-12-10 10:47

import apps.offer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0002_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='photo',
            name='is_main',
        ),
        migrations.AddField(
            model_name='offer',
            name='main_photo',
            field=models.ImageField(blank=True, upload_to=apps.offer.models.build_photo_path),
        ),
    ]
