# Generated by Django 4.1.3 on 2022-12-10 10:57

import apps.offer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0003_alter_photo_options_remove_photo_is_main_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='main_photo',
            field=models.ImageField(upload_to=apps.offer.models.build_photo_path),
        ),
    ]
