# Generated by Django 4.1.3 on 2022-12-14 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0006_alter_offer_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offer',
            options={'ordering': ['date_create']},
        ),
    ]
