# Generated by Django 4.1.3 on 2022-12-19 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
        ('offer', '0007_alter_offer_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='tags',
            field=models.ManyToManyField(related_name='tags', related_query_name='tag', to='tag.tag'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', related_query_name='photo', to='offer.offer'),
        ),
    ]
