# Generated by Django 4.1.3 on 2022-12-19 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
        ('offer', '0008_offer_tags_alter_photo_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', related_query_name='tag', to='tag.tag'),
        ),
    ]
