# Generated by Django 4.1.3 on 2022-12-23 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0009_alter_offer_tags'),
    ]

    operations = [
    ]
