# Generated by Django 4.1.3 on 2022-12-27 11:51

import apps.core.build_photo_path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0012_alter_offer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='description',
            field=models.TextField(null=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='main_photo',
            field=models.ImageField(null=True, upload_to=apps.core.build_photo_path.build_photo_path),
        ),
    ]
