# Generated by Django 4.1.3 on 2023-01-26 11:26

import apps.core.build_photo_path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0016_alter_offer_price_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='main_photo',
            field=models.ImageField(db_column='main_photo', null=True, upload_to=apps.core.build_photo_path.build_photo_path),
        ),
        migrations.RenameField(
            model_name='offer',
            old_name='main_photo',
            new_name='_main_photo',
        ),
    ]
