# Generated by Django 4.1.3 on 2023-01-26 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0017_alter_offer_main_photo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='_main_photo',
            new_name='main_photo',
        ),
    ]
