# Generated by Django 4.1.3 on 2023-02-03 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0022_rename__main_photo_offer_main_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='price_type',
            field=models.CharField(choices=[('hours', 'часы'), ('days', 'дни')], default='day', max_length=50, verbose_name='Цена за'),
        ),
    ]
