# Generated by Django 4.1.3 on 2023-02-17 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0024_alter_offer_price_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='weekend_price',
        ),
    ]
