FROM nikolaik/python-nodejs:python3.9-nodejs19-alpine

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN apk update && apk add bash && apk add postgresql-dev gcc python3-dev musl-dev

RUN pip install --upgrade pip
COPY ./requirements.txt .
RUN pip install -r requirements.txt

COPY . .

RUN cd ./crystallake/frontend && chmod -R a+x node_modules && npm install && npm run dev

ENTRYPOINT ./wait-for-it.sh db:5432 -- python3.9 manage.py migrate && python3.9 manage.py runserver 0.0.0.0:8000

