version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile_app
    container_name: app
    command: python3.9 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./crystallake/:/app/
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./.env

  db:
    image: postgres:15.1-alpine3.16
    container_name: db
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT_OUT}:${DB_PORT_DOCKER}
    env_file:
      - ./.env
