FROM ubuntu/apache2:2.4-20.04_edge

WORKDIR /app

RUN apt-get -y update
RUN apt-get install -y software-properties-common
RUN add-apt-repository -y ppa:deadsnakes/ppa
RUN apt-get install -y python3.9 python3-pip python3-dev libpq-dev libapache2-mod-wsgi-py3 nodejs npm nano

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN pip3 install --upgrade pip
COPY ./requirements.txt .
RUN pip3 install -r requirements.txt

COPY . .

COPY ./crystal_lake.conf /etc/apache2/sites-available/crystal_lake.conf
RUN a2enmod headers && service apache2 restart
RUN a2ensite crystal_lake.conf
RUN a2dissite 000-default.conf
EXPOSE 80

ENTRYPOINT  cd /app/frontend && npm install && \
            if [ $DEV = true ]; then npm run dev; else npm run build ; fi && \
            cd /app && chmod -R ugo+w /app/media /app/static /app/sms_codes.txt && \
            ./wait-for-it.sh db:5432 -- \
            python3 manage.py makemigrations && \
            python3 manage.py migrate && \
            python3 manage.py collectstatic --no-input && \
            apachectl -D FOREGROUND


