# Generated by Django 4.1.3 on 2022-12-27 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='beds',
            field=models.SmallIntegerField(null=True, verbose_name='спальных мест'),
        ),
        migrations.AlterField(
            model_name='room',
            name='floors',
            field=models.SmallIntegerField(null=True, verbose_name='этажей'),
        ),
        migrations.AlterField(
            model_name='room',
            name='rooms',
            field=models.SmallIntegerField(null=True, verbose_name='комнат'),
        ),
        migrations.AlterField(
            model_name='room',
            name='square',
            field=models.FloatField(null=True, verbose_name='площадь'),
        ),
    ]
