# Generated by Django 4.1.3 on 2022-12-29 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='зарплата')),
                ('additional_info', models.TextField(verbose_name='доп. информация')),
                ('qualifications', models.ManyToManyField(blank=True, related_name='workers', related_query_name='worker', to='service.service')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('user.customuser',),
        ),
    ]
