# Generated by Django 4.1.3 on 2022-12-31 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='additional_info',
            field=models.TextField(blank=True, null=True, verbose_name='доп. информация'),
        ),
    ]
