# Generated by Django 4.1.3 on 2022-12-23 10:31

import apps.core.build_photo_path
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offer', '0011_remove_room_main_room_remove_room_offer_ptr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.SmallIntegerField()),
                ('path', models.ImageField(upload_to=apps.core.build_photo_path.build_photo_path)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', related_query_name='photo', to='offer.offer')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
