# Generated by Django 4.1.3 on 2023-01-01 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionsProxy',
            fields=[
            ],
            options={
                'ordering': ['-id'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.permission',),
        ),
    ]
