# Generated by Django 4.1.3 on 2022-12-28 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0007_remove_customuser_bonuses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clist',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('bonuses', models.IntegerField(blank=True, default=0, verbose_name='Бонусов')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('user.customuser',),
        ),
    ]
