# Generated by Django 4.1.3 on 2023-01-22 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='bonuses',
        ),
    ]
