# Generated by Django 4.1.3 on 2022-12-28 12:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clist',
            new_name='Client',
        ),
    ]
