# Generated by Django 4.1.3 on 2023-02-17 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_remove_client_bonuses'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['-id']},
        ),
    ]
