# Generated by Django 4.1.3 on 2022-12-15 09:14

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_customuser_managers_customuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='837562631', max_length=128, region='RU', unique=True, verbose_name='Номер телефона'),
        ),
    ]
