# Generated by Django 4.1.3 on 2023-01-30 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_smscode_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='smscode',
            name='is_used',
            field=models.BooleanField(default=False, verbose_name='Использован'),
        ),
        migrations.AddField(
            model_name='smscode',
            name='request_code',
            field=models.TextField(default='2', unique=True, verbose_name='Иднетификатор запроса'),
        ),
    ]
