# Generated by Django 4.1.3 on 2022-12-28 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_customuser_options_customuser_bonuses_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='bonuses',
        ),
    ]
