# Generated by Django 4.1.3 on 2023-02-06 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_smscode_request_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='smscode',
            name='ip',
            field=models.CharField(default='qwerty', max_length=30, verbose_name='ip'),
        ),
        migrations.AddField(
            model_name='smscode',
            name='type',
            field=models.CharField(choices=[('register', 'регистрация'), ('password_reset', 'сброс пароля')], default='register', max_length=50, verbose_name='Тип запроса'),
        ),
    ]
