# Generated by Django 4.1.3 on 2023-02-15 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_smscode_ip_smscode_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smscode',
            name='ip',
            field=models.CharField(max_length=30, verbose_name='ip'),
        ),
    ]
