# Generated by Django 4.1.3 on 2022-12-23 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offer', '0011_remove_room_main_room_remove_room_offer_ptr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('offer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='offer.offer')),
                ('max_for_moment', models.SmallIntegerField(verbose_name='макс. единовременно')),
                ('dynamic_timetable', models.BooleanField(verbose_name='динамическое расписание')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('offer.offer',),
        ),
    ]
