# Generated by Django 4.1.3 on 2023-01-16 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_servicetimetable_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicetimetable',
            options={'ordering': ['id']},
        ),
    ]
