# Generated by Django 4.1.3 on 2023-01-21 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_service_max_intersections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='max_intersections',
            field=models.SmallIntegerField(default=0, verbose_name='макс пересечений'),
        ),
    ]
