# Generated by Django 4.1.3 on 2023-01-21 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_alter_service_max_intersections'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='dynamic_timetable',
        ),
    ]
