# Generated by Django 4.1.3 on 2023-02-06 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_remove_service_dynamic_timetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='min_time',
            field=models.SmallIntegerField(default=30, verbose_name='мин. время брони'),
        ),
    ]
