# Generated by Django 4.1.3 on 2023-02-16 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_service_min_time'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='servicetimetable',
            name='service_ser_start_1b5bd0_idx',
        ),
        migrations.AddIndex(
            model_name='servicetimetable',
            index=models.Index(fields=['service_id', 'start', 'end'], name='service_ser_service_c7a7ec_idx'),
        ),
    ]
